### ISSUE TITLE
problem with version 115, it does not find a version

### ISSUE THREAD

**Issue by juanfrilla** [yeongbin-jo/python-chromedriver-autoinstaller#58]
problem with version 115, it does not find a version

**Comment by juanfrilla** [comment]
thanks @abcdec updated to 0.6.2

**Comment by shawnCaza** [comment]
See the discussion in #53 .

The problem is Chrome has different versions for a/b testing that do not have drivers. If you happened to get the 'b' version of the browser release instead of the 'a' version, then it won't find the driver for your browser.

We have multiple PR trying to fix this in different ways. I'm sure the library will be updated with a robust solution soon.

**Comment by andrew-geeks** [comment]
Even i have the same issue. chromedriver-autoinstaller outputs "WARNING:root:Can not find chromedriver for currently installed chrome version(115.0.5790.110)" for the current chrome version. Any solutions?

**Comment by abcdec** [comment]
@shawnCaza

> Did you have the driver for '115.0.5790.102' already installed when you attempted to get 115.0.5790.110?

Yes and no, I have multiple environment. I had the issue Friday last week on one of my execution environment when the Chrome version in the environment was still `115.0.5790.102`.  The issue was resolved by 0.6.2 Monday. In that environment, Web testing did work fine with the combination of `115.0.5790.102` WebDriver and `115.0.5790.110` Chrome after Chrome is switched to  `115.0.5790.110`, but a precheck script started throwing an exception because `new_driver_folder = chromedriver_autoinstaller.install(driver_folder)` started returning None instead of the path string, which was worked around locally.  On the other hand, I needed another scratch install on another execution environment. 0.6.2 does not download the stable `115.0.5790.102` when Chrome version `115.0.5790.110` is installed.  There are several manual workarounds, so I can live with the issue for now, but expecting it is eventually fixed.

@juanfrilla, @andrew-geeks, yes that's my understanding, 0.6.2 still has the problem finding the driver if Chrome version is switched 115.0.5790.110, probably because 115.0.5790.110 driver is not yet stable, and it seems chromedriver_autoinstaller  looks for entire version string match.  If it were finding only the major version match, it could've worked OK.

```
PS C:\Temp> pip install --upgrade chromedriver_autoinstaller
Requirement already satisfied: chromedriver_autoinstaller in c:\program files\python311\lib\site-packages (0.6.2)
PS C:\Temp> python
Python 3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import chromedriver_autoinstaller
>>> driver_folder = 'C:/Temp'
>>> new_driver_folder = chromedriver_autoinstaller.install(driver_folder)
WARNING:root:Can not find chromedriver for currently installed chrome version.
>>> print('new_driver_folder: ' + str(new_driver_folder))
new_driver_folder: None
>>> print('chrome version: ' + str(chromedriver_autoinstaller.get_chrome_version()))
chrome version: 115.0.5790.110
>>> exit()
PS C:\Temp>
```

![image](https://github.com/yeongbin-jo/python-chromedriver-autoinstaller/assets/7719670/4ddde7a8-3d66-45fc-8314-49e9486c4158)
(as of Sat Jul 29 04:43:16 PM UTC 2023)

**Comment by shawnCaza** [comment]
Thanks @abcdec  for the precision. This is helpful.

I think either #54 or #57 offer an improvement on 0.6.2. Feel free to test them out, but all the details may not be perfect yet.

**Comment by abcdec** [comment]
@shawnCaza I tested #54 and #57 and left comment/logs there in respective PR. (short summary is that both worked fine for my use case.)  Hope either solution will be available in formal release through pip soon, thanks for the effort.

**Comment by GQAssurance** [comment]
Both look good to me, #57 looks more elegant.

**Comment by shawnCaza** [comment]
Thanks @GQAssurance, to be fair to #54 I believe @max32002 is trying to incorporate the changes I made in #57, but is also attempting to address a number of other topics that have come up.

I haven't had a chance to look at everything in #54 carefully yet, but I believe there's some other good ideas in there.

**Comment by Chetan11-dev** [comment]
This is a Temporary Bug due which occurs in Chrome 115.  The fix is to:

1. Go to https://googlechromelabs.github.io/chrome-for-testing/#stable and download "chrome driver" based on your chrome version.
2. Extract the zip file
3. Please place the "chromedriver" file (or "chromedriver.exe" if you are using Windows) directly into the desired location. Make sure you're not placing the extracted folder but only the chrome driver file itself.
    

    ![Screenshot (520).png](https://chetan-jain-omkar.notion.site/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2Ff7ddfb18-ad8e-492c-83a2-1b2e65faeda2%2FScreenshot_(520).png?table=block&id=de77211e-a7da-4149-ad02-33338569af27&spaceId=8fb8cd62-9b0a-4bc4-bdb3-dc442b11cf8a&width=920&userId=&cache=v2)

**Comment by GQAssurance** [comment]
@Chetan11-dev you are correct that manually downloading the webdriver does indeed workaround the problem of this library not downloading the driver....

But I don't think this is a "bug" and certainly not within Chrome.   It appears to be a misunderstanding/bad assumption on my part that Google would always publish a newly versioned Chromedriver release in lockstep with every newly versioned Chrome release .

**Comment by Chetan11-dev** [comment]
Apology for considering it to be a bug.

**Comment by GQAssurance** [comment]
> Apology for considering it to be a bug.

There is indeed a bug.  What I meant to say is that the bug is within this library but not within Chrome.  Nothing to apologize for!

**Comment by GQAssurance** [comment]
> Thanks @GQAssurance, to be fair to #54 I believe @max32002 is trying to incorporate the changes I made in #57, but is also attempting to address a number of other topics that have come up.
> 
> I haven't had a chance to look at everything in #54 carefully yet, but I believe there's some other good ideas in there.

As a general rule, I prefer not to mix improvements in with bugfix PRs.

You are particularly active in the discussions & updating your PR, so I trust your PR a bit more from a quality POV.

However I have a low attachment to any particular solution.  I just hope 1 of the 2 (now 3?) fixes being offered is chosen & merged soon.

**Comment by Saif600** [comment]
There is a problem while matching the current version of Chrome [not CFT]. The current version of Chrome is "**115.0.5790.171**" So when autoinstaller is fetching the version from the machine[**windows**] it returns "115.0.5790.171". When it is going to find the URL and matches the version with the available one from JSON, autoinstaller fails because the stable version available is "115.0.5790.170". However, chromedriver for "**115.0.5790.170"** is working for Chrome version **115.0.5790.171**. Are you going to handle the issue? 
Note: webdriver_manager can handle this issue. Thanks.

**Comment by shawnCaza** [comment]
@Saif600 Feel free to test #57 I believe it will resolve you issue.

**Comment by Saif600** [comment]
@shawnCaza, the version package handles the issue. It is working now. Thanks for the update

**Comment by GQAssurance** [comment]
I think it's time to move onto an alternate package to handle Chromedriver.    We've had at least 2 working branches for weeks now and neither of them published.

**Comment by juanfrilla** [comment]
@GQAssurance it's time to use an alternative of Selenium like playwright or ichrome, Selenium it's prone to errors consuming a lot of resources, verbosing all stuff and making all of this more difficult than it really is.

**Comment by GQAssurance** [comment]
> @GQAssurance it's time to use an alternative of Selenium like playwright or ichrome, Selenium it's prone to errors consuming a lot of resources (spawning a browser and a chromedriver), verbosing all the stuff and making all of this more difficult than it really is.

@juanfrilla Selenium is merely popular collection of implementations of the WebDriver protocol, but not the only one.  While Selenium requires Chromedriver to drive a Chrome instance, Chromedriver doesn't require Selenium to be issuing the commands.

This library is about solving the specific problem of managing Chromedriver binary downloads.

The question of "_should a particular user switch to an alternative to WebDriver protocol to automate their browsers_" is well outside the scope of this issue & this repository, IMO.

**Comment by juanfrilla** [comment]
@GQAssurance so if my comment was outside of the scope of this issue, your comment its outside as well.
Because you propose to use an alternative like me and I answer to you in an issue that I created.
For that motive Im going to close this.

**Comment by Chetan11-dev** [comment]
I created a fork named `chromedriver-autoinstaller-fix` to address this problem.

## Installation

```bash
pip install chromedriver-autoinstaller-fix
```

## Example

```python
from selenium import webdriver
import chromedriver_autoinstaller_fix

chromedriver_autoinstaller_fix.install()  
# Check if the current version of chromedriver exists
# and if it doesn't, download it automatically,
# then add chromedriver to path

driver = webdriver.Chrome()
driver.get("http://www.python.org")
assert "Python" in driver.title
```

## I would greatly appreciate a Star [here](https://github.com/omkarcloud/chromedriver-autoinstaller-fix) :)
